export { ReactiveFieldErrorsComponent } from './lib/components/field-errors/reactive-forms/field-errors.component';
export { SignalFieldErrorsComponent } from './lib/components/field-errors/signal-forms/field-errors.component';
export { LoaderComponent } from './lib/components/loader/loader.component';
export { ScrollToFirstErrorDirective } from './lib/directives/scroll-to-error.directive';
export { scrollToFirstError } from './lib/helpers/scroll-to-first-error';
export { REGEX, type RegexKey } from './lib/forms/regex';
export { phoneSchema } from './lib/forms/phone.schema';
export { phoneValidator } from './lib/forms/phone.validator';
export { errorInterceptor } from './lib/interceptors/error.interceptor';
export { loaderInterceptor } from './lib/interceptors/loader.interceptor';
export { ErrorService } from './lib/services/error.service';
export { LoaderService } from './lib/services/loader.service';
